### PR TITLE
I added my files for an analog clock 😁

### PR DESCRIPTION
**Pull request by umadhatri**
Hey guys, I added my files for an analog computer and there is an extra file called DS Store that I am not able to get rid of. But, the rest all are my files 😊

### CODE REVIEW

**Review by ashwinexe — CHANGES_REQUESTED** [review]
Hey, I see unused files here with `.DS_Store` extension. 
If you cannot remove them from PC while committing, you can remove them directly from github.
like this 
image

**Comment by umadhatri** [comment]
Hey, I removed the extension file

**Review by ashwinexe — APPROVED** [review]
LGTM

**Comment by ashwinexe** [comment]
Your clock has been added. (yay!)

**Comment by umadhatri** [comment]
Yay!

**Pull request merged**
